// Chapter 11/Start-Part3/SpyStore.Angular2/ClientApp/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { ProductService } from '../services/product.service';
import { LoggingService } from '../services/logging.service';

@Component({
  templateUrl: './products.component.html',
})
export class ProductsComponent implements OnInit {
  products: any[];
  header: string;

  constructor(private _service: ProductService, private _loggingService: LoggingService) { }

  ngOnInit() {
    this._service.getFeaturedProducts().subscribe(products => {
      this.header = 'Featured Products';
      this.products = products;
  }, err => this._loggingService.logError('Error Loading Featured Products', err));

  }
}

<div class="jumbotron">
  <a routerLink="/products" class="btn btn-info btn-lg">View Tech Deals &raquo;</a>
</div>

<h3>{{header}}</h3>

<div class="row">
  <div class="col-6 col-sm-4 col-md-3" *ngFor="let product of products">
    <div class="product">
      <img [src]="'images/' + product.Details.ProductImage" />
      <div class="price">{{product.CurrentPrice | currency:'USD':symbol:'1.2-2'}}</div>
      <div class="title-container">
        <h5>{{product.Details.ModelName}}</h5>
      </div>
      <div class="model-number"><span class="text-muted">Model Number:</span> {{product.ModelNumber}}</div>
      <a [routerLink]="['/products', product.CategoryId]" class="category">{{product.CategoryName}}</a>
      <a [routerLink]="['/product', product.Id]" class="btn btn-primary btn-cart"><span class="fa fa-shopping-cart"></span> Add to Cart</a>
    </div>
  </div>
</div>

// Chapter 12/src/components/products.tsx
﻿import * as React from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Client, Product } from '../services/api.client';

interface ProductsState {
  header: string;
  products: Product[];
  categoryId: number | null;
}

export class Products extends React.Component<RouteComponentProps<{ id: string | null }>, ProductsState> {

  constructor(props) {
    super(props);
    this.state =  { header: '', products: [], categoryId: null };
  }

  componentDidMount() {
    this.refreshProducts();
  }

  componentDidUpdate(prevProps, prevState) {

    if (this.props.match && +this.props.match.params.id !== +prevProps.match.params.id) {
      this.refreshProducts();
    }
  }

  refreshProducts() {
    if (!this.props.match || !this.props.match.params.id) {
      this.loadFeaturedProducts();
    } else if (+this.props.match.params.id !== this.state.categoryId) {
      this.loadCategoryProducts(+this.props.match.params.id);
    }
  }

  loadFeaturedProducts() {
    const client = new Client(process.env.REACT_APP_SPYSTORE_API_URL);

    client.getFeaturedProducts().then((data) => {
      this.setState({ categoryId: null, header: 'Featured Products', products: data });
    }).catch(err => {
      this.setState( {categoryId: this.state.categoryId, header: '[Error Loading Products]', products: []});
      console.log(err);
    });
  }

  loadCategoryProducts(categoryId: number) {
    const client = new Client(process.env.REACT_APP_SPYSTORE_API_URL);

    client.getCategoryProducts(categoryId).then((data) => {
      const categoryName = data.length > 0 ? data[0].categoryName : 'Category';
      this.setState({ header: categoryName, products: data, categoryId: categoryId });
    }).catch(err => {
      this.setState( {categoryId: this.state.categoryId, header: '[Error Loading Products]', products: []});
      console.log(err);
    });
  }

  searchProducts(searchText: string) {
    const client = new Client(process.env.REACT_APP_SPYSTORE_API_URL);

    client.searchProducts(searchText).then((data) => {
      this.setState({ header: 'Search Results', products: data, categoryId: null });
    }).catch(err => {
      this.setState( {categoryId: this.state.categoryId, header: '[Error Loading Products]', products: []});
      console.log(err);
    });
  }

  render() {


    const featuredLink = this.state.header === 'Featured Products' ? <div/> :
                       <Link to='/' className="btn btn-info btn-lg">View Featured Products</Link>;

    const products = this.state.products.map((product) => {
      const imageUrl = '/images/' + product.details.productImage;
      const isCurrentCategory = this.state.categoryId === product.categoryId;

      return (<div key={ product.id.toString() } className="col-xs-6 col-sm-4 col-md-3">
        <div className="product">
          <img src={ imageUrl }/>
          <div className="price">${ product.currentPrice.toFixed(2) }</div>
          <div className="title-container">
            <h5>{ product.details.modelName }</h5>
          </div>
          <div className="model-number">
            <span className="text-muted">Model Number:</span> { product.details.modelNumber }</div>
          { (isCurrentCategory) ? (
                                  <Link to={ 'products/' + product.categoryId } className="category">{ product.categoryName }</Link>) :
            (<div className="category">{ product.categoryName }</div>) }
          <Link to={ '/product/' + product.id }
                className="btn btn-primary btn-cart"><span className="glyphicon glyphicon-shopping-cart"/> Add to
            Cart</Link>
        </div>
      </div>);
    });

    return <div>
      <div className="jumbotron">
        { featuredLink }
      </div>

      <h3>{ this.state.header }</h3>

      <div className="row">
        { products }
      </div>
    </div>;
  }
}
