// Chapter 12/src/components/cartRecord.tsx
﻿import * as React from "react";
import { Link } from "react-router-dom";
import {CartRecordWithProductInfo} from "../services/api.client";

interface CartRecordState {
    quantity: number;
    item: CartRecordWithProductInfo | null;
}

interface CartRecordProps {
    item: CartRecordWithProductInfo;
    updateQuantity: (item: CartRecordWithProductInfo) => void;
    onRowDeleted: (item: CartRecordWithProductInfo) => void;
}

export class CartRecord extends React.Component<CartRecordProps, CartRecordState> {

    constructor(props) {
        super(props);
        this.state = {quantity: -1, item: null };
    }

    componentDidMount() {
        this.setState({quantity: this.props.item.quantity, item: this.props.item});
    }

    quantityUpdated(event) {

        var quantity: number = Number(event.target.value);

        if (quantity > this.state.item.unitsInStock) {
            quantity = this.state.item.unitsInStock;
        }
        else if (quantity < 1) {
            quantity = 1;
        }

        let item = this.state.item;

        item.quantity = quantity;

        this.setState({quantity: quantity, item: item});
    }

    updateQuantity() {
        if (this.props.updateQuantity) {
            this.props.updateQuantity(this.state.item);
        }
    }

    removeRow() {
        if (this.props.onRowDeleted) {
            this.props.onRowDeleted(this.state.item);
        }
    }

    render() {
        return <tr>
            <td>
                <div className="product-cell-detail">
                    <img src="images/product-thumb.png" className="pull-left"/>
                    <Link to={'/product/' + this.props.item.productId }
                          className="h5">{ this.props.item.modelName }</Link>
                    <div className="small text-muted hidden-xs">{ this.props.item.description }</div>
                </div>
            </td>
            <td className="text-right">${ this.props.item.currentPrice.toFixed(2) }</td>
            <td className="text-right cart-quantity-row">
                <input type="number" className="cart-quantity" value={ this.state.quantity }
                       onChange={ (e) => this.quantityUpdated(e) }/>
                <button className="btn btn-link btn-sm" onClick={ () => this.updateQuantity() }>Update</button>
                <button className="btn btn-link btn-sm" onClick={ () => this.removeRow() }>Remove</button>
            </td>
            <td className="text-right">{ this.props.item.unitsInStock }</td>
            <td className="text-right">${ this.props.item.lineItemTotal.toFixed(2) }</td>
        </tr>
    }
}

// Chapter 11/End-Part3/SpyStore.Angular2/ClientApp/src/app/cart-record/cart-record.component.ts
import {Component, Input, Output, EventEmitter} from '@angular/core';
import {CartService, ShoppingCartRecord} from '../services/cart.service';
import {LoggingService} from '../services/logging.service';

@Component({
    // tslint:disable-next-line:component-selector
    selector: '[cart-record]',
    templateUrl: './cart-record.component.html',
})
export class CartRecordComponent {
    @Input() record: ShoppingCartRecord;
    @Output() recordRemoved = new EventEmitter<ShoppingCartRecord>();

    constructor(private _cartService: CartService, private _loggingService: LoggingService) { }

    updateItem() {
        this.record.LineItemTotal = this.record.Quantity * this.record.CurrentPrice;
        this._cartService.updateCartRecord(this.record).subscribe((response) => {
            if (response.status === 201) {
                this._cartService.getCartRecord(this.record).subscribe(newRecord => {
                    this.record.TimeStamp = newRecord.TimeStamp;
                });
            }
        }, err => this._loggingService.logError('Error Updating Cart Item', err),
        () => console.log('Update Complete'));
    }

    removeItem() {
        this._cartService.removeCartRecord(this.record).subscribe((response) => {
            if (response.status === 204) {
                this.recordRemoved.emit(this.record);
            }
        }, err => this._loggingService.logError('Error Deleting Cart Item', err),
        () => console.log('Delete Complete'));
    }
}

﻿<td>
    <div class="product-cell-detail">
        <img src="images/product-thumb.png" class="pull-left" />
        <a [routerLink]="['/product', record.ProductId]" class="h5">{{record.ModelName}}</a>
        <div class="small text-muted hidden-xs">{{record.Description}}</div>
    </div>
</td>
<td class="text-right">{{record.CurrentPrice | currency:'USD':symbol:'1.2-2'}}</td>
<td class="text-right cart-quantity-row">
    <input type="number" [(ngModel)]="record.Quantity" class="cart-quantity" />
    <button class="btn btn-link btn-sm" (click)="updateItem()">Update</button>
    <button class="btn btn-link btn-sm" (click)="removeItem()">Remove</button>
</td>
<td class="text-right">{{record.UnitsInStock }}</td>
<td class="text-right">{{record.LineItemTotal | currency:'USD':symbol:'1.2-2'}}</td>
